version: '2.15.1'

services:
  anoc-db:
    image: mysql:8.0.32
    restart: unless-stopped
    container_name: dev_anoc_db
    ports:
      - '3306:3306'
      - '3306'
    environment:
      MYSQL_DATABASE: 'dev_anoc_db'
      MYSQL_USER: 'dev_anoc_db_user'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'